version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: gps_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  mongodb:
    image: mongo:latest
    container_name: gps_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  redis_data:
  mongodb_data:
