# Generated by Django 5.1.3 on 2024-11-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.CharField(choices=[('mouton', 'Mouton'), ('chat', 'Chat'), ('chien', 'Chien')], default='mouton', max_length=50),
        ),
    ]
