# Generated by Django 4.2.10 on 2024-11-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('battery', models.FloatField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('is_inside_geofence', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['animal_id', '-timestamp'], name='mqtt_topics_animal__00c2a5_idx')],
            },
        ),
    ]
